project:
  type: book
  output-dir: docs

book:
  title: "Data Literacy"
  author: "Rodney Dyer"
  date: "12/8/2022"
  chapters:
    - index.qmd
    - narrative_BasicDataTypes.qmd
    - narrative_DataContainers.qmd
    - narrative_Factors.qmd
    - narrative_Tidyverse.qmd
    - narrative_Joins.qmd
    - narratvive_Spatial.qmd
    - narrative_Raster.qmd
    - narrative_Shapefiles.qmd
  
  execute:
    echo: true

bibliography: references.bib

format:
  html:
    theme: cosmo



