project:
  type: book
  output-dir: docs

book:
  title: "Data Literacy"
  author: "Rodney Dyer"
  date: "12/8/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  execute:
    echo: true

bibliography: references.bib

format:
  html:
    theme: cosmo



